# Generated by Django 3.2.7 on 2021-09-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPergunta', models.CharField(blank=True, default='', max_length=30, verbose_name='código da Pergunta')),
                ('pergunta', models.CharField(blank=True, default='', max_length=500, verbose_name='Pergunta')),
            ],
            options={
                'ordering': ('codigoPergunta',),
            },
        ),
        migrations.CreateModel(
            name='Quintil_Riqueza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, default='', max_length=10, verbose_name='Resposta')),
                ('codigoPergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riquezaCodigoPergunta', to='questionario.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='historico_Saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, default='', max_length=10, verbose_name='Resposta')),
                ('codigoPergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saudeCodigoPergunta', to='questionario.pergunta')),
            ],
        ),
    ]
