# Generated by Django 3.2.7 on 2021-09-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_saude',
            name='codigoPergunta',
        ),
        migrations.RemoveField(
            model_name='quintil_riqueza',
            name='codigoPergunta',
        ),
        migrations.AddField(
            model_name='historico_saude',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saudePergunta', to='questionario.pergunta'),
        ),
        migrations.AddField(
            model_name='quintil_riqueza',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riquezaPergunta', to='questionario.pergunta'),
        ),
    ]
