# Generated by Django 3.2.7 on 2021-09-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametro', '0001_initial'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_turmaMatricula', to='aluno.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_turmaTurma', to='parametro.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(blank=True, default='', max_length=15, verbose_name='Número de Processo')),
                ('ano_lectivo', models.DateField(blank=True, null=True, verbose_name='Ano Lectivo')),
                ('conferido', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Status da matrícula (se foi validada ou não)')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculaAluno', to='aluno.aluno')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculaClasse', to='parametro.classe')),
            ],
            options={
                'ordering': ('numero_processo',),
            },
        ),
    ]
