# Generated by Django 3.2.7 on 2021-09-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0001_initial'),
        ('aluno', '0002_auto_20210925_2202'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculaAluno', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculaClasse', to='parametro.classe'),
        ),
        migrations.AlterField(
            model_name='matricula_turma',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_turmaMatricula', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='matricula_turma',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_turmaTurma', to='parametro.classe'),
        ),
    ]
