# Generated by Django 3.2.7 on 2021-09-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encarregado',
            old_name='Profissao',
            new_name='profissao',
        ),
        migrations.RenameField(
            model_name='filiacao',
            old_name='ProfissaoMae',
            new_name='profissaoMae',
        ),
        migrations.RenameField(
            model_name='filiacao',
            old_name='ProfissaoPai',
            new_name='profissaoPai',
        ),
        migrations.AddField(
            model_name='encarregado',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=250, unique=True, verbose_name='Email do Encarregado/a'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=250, unique=True, verbose_name='Email do Aluno/a'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='encarregado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudanteEncarregado', to='aluno.encarregado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudanteEndereco', to='aluno.endereco'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='filiacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudanteFiliacao', to='aluno.filiacao'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudanteTelefone', to='aluno.telefone'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encarregadoEndereco', to='aluno.endereco'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='nameEncarregado',
            field=models.CharField(blank=True, default='', max_length=350, verbose_name='Nome do Encarregado/a'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encarregadoTelefone', to='aluno.telefone'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiacaoEndereco', to='aluno.endereco'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='telefone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiacaoTelefone', to='aluno.telefone'),
        ),
    ]
