# Generated by Django 3.2.7 on 2021-09-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeClasse', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Sala')),
            ],
            options={
                'ordering': ('nomeClasse',),
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Hora de início')),
                ('hora_fim', models.DateTimeField(blank=True, default='', max_length=50, verbose_name='Hora do fim')),
                ('periodo', models.CharField(blank=True, default='', max_length=50, verbose_name='Periodo')),
                ('turno', models.CharField(blank=True, default='', max_length=50, verbose_name='Turno')),
            ],
            options={
                'ordering': ('periodo',),
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSala', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da Sala')),
                ('capacidade', models.CharField(blank=True, default='', max_length=50, verbose_name='Capacidade')),
                ('tipoSala', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de Sala')),
            ],
            options={
                'ordering': ('nameSala',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTurma', models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Turma')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmaPeriodo', to='parametro.periodo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmaSala', to='parametro.sala')),
            ],
            options={
                'ordering': ('nameTurma',),
            },
        ),
    ]
