# Generated by Django 3.2.7 on 2021-09-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDisciplina', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
            ],
        ),
        migrations.AlterField(
            model_name='classe',
            name='nomeClasse',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Classe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='disciplina',
            field=models.ManyToManyField(to='parametro.Disciplina'),
        ),
    ]
